Repository ubclaunchpad/forum, pull requests merged in 2025-03, with the labels that each got.

#326 bullet point bug fix
  frontend/src/components/general/EditorComponent.tsx
Labels: bug

#327 Google analytics Tracking
  frontend/src/app/auth/finish-setup/actions.ts
  frontend/src/app/auth/finish-setup/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/lib/utils.ts
  frontend/src/utils/supabase/server.ts
Labels: devOps

#335 Update Readme documentation for supabase
  README.md
Labels: documentation

#341 Courses migration of create, delete and get course by id
  server/supabase/functions/_dev/setup.ts
  server/supabase/functions/courses/controller/add_course_member_activity.ts
  server/supabase/functions/courses/controller/create_course_activity.ts
  server/supabase/functions/courses/controller/delete_course_activity.ts
  server/supabase/functions/courses/controller/get_all_courses_activity.ts
  server/supabase/functions/courses/controller/get_course_activity.ts
  server/supabase/functions/courses/index.ts
  server/supabase/functions/tests/courses/integrated/create_course_test.ts
  server/supabase/functions/tests/courses/integrated/delete_course_test.ts
  server/supabase/functions/tests/courses/integrated/get_course_test.ts
  server/supabase/functions/tests/posts/integrated/posts_test.ts
  server/supabase/functions/tests/shared/test_data.ts
  server/supabase/functions/tests/users/integrated/users/user_test.ts
  server/supabase/migrations/20250303074149_initial_setup.sql
  server/supabase/migrations/seed.sql
  server/supabase/seed.sql
  shared/schema/course.ts
Labels: migration
